version: '3.0'
services:
  db:
    image: mongo
    restart: always
    container_name: vlc_tips_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: development
      MONGO_INITDB_DATABASE: vlctips
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express
    depends_on:
        - db
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_SERVER: db
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
        ME_CONFIG_MONGODB_ADMINPASSWORD: development
